package opera

import "encoding/xml"

// TRIALBALANCE was generated 2024-09-05 14:32:20 by https://xml-to-go.github.io/ in Ukraine.
type TrialBalance struct {
	XMLName      xml.Name `xml:"TRIAL_BALANCE"`
	LISTGTRXTYPE struct {
		GTRXTYPE []struct {
			TRXTYPESORT        string `xml:"TRX_TYPE_SORT"`
			TRXTYPE            string `xml:"TRX_TYPE"`
			TRXTYPEDESCRIPTION string `xml:"TRX_TYPE_DESCRIPTION"`
			ISTBTRXTYPE01      string `xml:"IS_TB_TRX_TYPE_01"`
			LISTGTRXCODE       struct {
				GTRXCODE []struct {
					TRXCODESORT          string  `xml:"TRX_CODE_SORT"`
					TRXCODE              string  `xml:"TRX_CODE"`
					DESCRIPTION          string  `xml:"DESCRIPTION"`
					TBAMOUNT             float64 `xml:"TB_AMOUNT"`
					TRXDATE              Date    `xml:"TRX_DATE"`
					NETAMOUNT            float64 `xml:"NET_AMOUNT"`
					GUESTLEDDEBIT        float64 `xml:"GUEST_LED_DEBIT"`
					GUESTLEDCREDIT       float64 `xml:"GUEST_LED_CREDIT"`
					ARLEDDEBIT           float64 `xml:"AR_LED_DEBIT"`
					ARLEDCREDIT          float64 `xml:"AR_LED_CREDIT"`
					DEPLEDDEBIT          float64 `xml:"DEP_LED_DEBIT"`
					DEPLEDCREDIT         float64 `xml:"DEP_LED_CREDIT"`
					PACKAGELEDDEBIT      float64 `xml:"PACKAGE_LED_DEBIT"`
					PACKAGELEDCREDIT     float64 `xml:"PACKAGE_LED_CREDIT"`
					INHDEBIT             float64 `xml:"INH_DEBIT"`
					INHCREDIT            float64 `xml:"INH_CREDIT"`
					NONREVENUEAMT        float64 `xml:"NON_REVENUE_AMT"`
					TODAYSACCRUALS       float64 `xml:"TODAYS_ACCRUALS"`
					DEPOSITATCHECKIN     float64 `xml:"DEPOSIT_AT_CHECKIN"`
					PACKAGELEDTAX        float64 `xml:"PACKAGE_LED_TAX"`
					DEPTAXLEDDEBIT       float64 `xml:"DEP_TAX_LED_DEBIT"`
					OWNERLEDDEBIT        float64 `xml:"OWNER_LED_DEBIT"`
					OWNERLEDCREDIT       float64 `xml:"OWNER_LED_CREDIT"`
					DEPLEDDEBITPLCZ      float64 `xml:"DEP_LED_DEBIT_PL_CZ"`
					LISTGCURRENCYDETAILS string  `xml:"LIST_G_CURRENCY_DETAILS"`
					CSCURRENCYCOUNT      float64 `xml:"CS_CURRENCY_COUNT"`
				} `xml:"G_TRX_CODE"`
			} `xml:"LIST_G_TRX_CODE"`
			CSTBAMOUNTTYPE float64 `xml:"CS_TB_AMOUNT_TYPE"`
		} `xml:"G_TRX_TYPE"`
	} `xml:"LIST_G_TRX_TYPE"`
	LISTGCHKBALANCE struct {
		GCHKBALANCE []struct {
			CHKBALCODE  string `xml:"CHK_BAL_CODE"`
			CHKBALVALUE string `xml:"CHK_BAL_VALUE"`
		} `xml:"G_CHK_BALANCE"`
	} `xml:"LIST_G_CHK_BALANCE"`
	CSTBAMOUNTREP           float64 `xml:"CS_TB_AMOUNT_REP"`
	CSGUESTLEDDEBITREP      float64 `xml:"CS_GUEST_LED_DEBIT_REP"`
	CSGUESTLEDCREDITREP     float64 `xml:"CS_GUEST_LED_CREDIT_REP"`
	CSARLEDDEBITREP         float64 `xml:"CS_AR_LED_DEBIT_REP"`
	CSARLEDCREDITREP        float64 `xml:"CS_AR_LED_CREDIT_REP"`
	CSDEPOSITLEDDEBITREP    float64 `xml:"CS_DEPOSIT_LED_DEBIT_REP"`
	CSDEPOSITLEDCREDITREP   float64 `xml:"CS_DEPOSIT_LED_CREDIT_REP"`
	CSPACKAGELEDDEBITREP    float64 `xml:"CS_PACKAGE_LED_DEBIT_REP"`
	CSPACKAGELEDCREDITREP   float64 `xml:"CS_PACKAGE_LED_CREDIT_REP"`
	CFGUESTLEDREP           float64 `xml:"CF_GUEST_LED_REP"`
	CFARLEDREP              float64 `xml:"CF_AR_LED_REP"`
	CFDEPOSITLEDREP         float64 `xml:"CF_DEPOSIT_LED_REP"`
	CFPACKAGELEDREP         float64 `xml:"CF_PACKAGE_LED_REP"`
	CPGUESTLEDDEBITYEST     float64 `xml:"CP_GUEST_LED_DEBIT_YEST"`
	CPGUESTLEDCREDITYEST    float64 `xml:"CP_GUEST_LED_CREDIT_YEST"`
	CPARLEDDEBITYEST        float64 `xml:"CP_AR_LED_DEBIT_YEST"`
	CPARLEDCREDITYEST       float64 `xml:"CP_AR_LED_CREDIT_YEST"`
	CPDEPOSITLEDDEBITYEST   float64 `xml:"CP_DEPOSIT_LED_DEBIT_YEST"`
	CPDEPOSITLEDCREDITYEST  float64 `xml:"CP_DEPOSIT_LED_CREDIT_YEST"`
	CPPACKAGELEDDEBITYEST   float64 `xml:"CP_PACKAGE_LED_DEBIT_YEST"`
	CPPACKAGELEDCREDITYEST  float64 `xml:"CP_PACKAGE_LED_CREDIT_YEST"`
	CPTBBALANCEYEST         float64 `xml:"CP_TB_BALANCE_YEST"`
	CFGUESTLEDYEST          float64 `xml:"CF_GUEST_LED_YEST"`
	CFCALCPREVIOUSBALANCE   float64 `xml:"CF_CALC_PREVIOUS_BALANCE"`
	CFARLEDYEST             float64 `xml:"CF_AR_LED_YEST"`
	CFDEPOSITLEDYEST        float64 `xml:"CF_DEPOSIT_LED_YEST"`
	CFPACKAGELEDYEST        float64 `xml:"CF_PACKAGE_LED_YEST"`
	CFTBBALANCETODAY        float64 `xml:"CF_TB_BALANCE_TODAY"`
	CPINHDEBITYEST          float64 `xml:"CP_INH_DEBIT_YEST"`
	CPINHCREDITYEST         float64 `xml:"CP_INH_CREDIT_YEST"`
	CFINHYEST               float64 `xml:"CF_INH_YEST"`
	CSINHDEBITREP           float64 `xml:"CS_INH_DEBIT_REP"`
	CSINHCREDITREP          float64 `xml:"CS_INH_CREDIT_REP"`
	CFINHREP                float64 `xml:"CF_INH_REP"`
	CFFUTUREACCRUALS        float64 `xml:"CF_FUTURE_ACCRUALS"`
	CFPACKAGELEDTODAY       float64 `xml:"CF_PACKAGE_LED_TODAY"`
	CPPACKAGEACCRUALS       float64 `xml:"CP_PACKAGE_ACCRUALS"`
	CFTBMSG                 string  `xml:"CF_TBMSG"`
	CSACCRUALSTODAY         float64 `xml:"CS_ACCRUALS_TODAY"`
	CFBALANCETODAY          float64 `xml:"CF_BALANCE_TODAY"`
	CSDEPOSITATCHECKIN      float64 `xml:"CS_DEPOSIT_AT_CHECKIN"`
	CFBALCARRIEDFORWARD     float64 `xml:"CF_BAL_CARRIED_FORWARD"`
	CFDEPOSITACTIVITYREP    float64 `xml:"CF_DEPOSIT_ACTIVITY_REP"`
	CFHOTELLEDGERTODAY      float64 `xml:"CF_HOTEL_LEDGER_TODAY"`
	CPPACKAGELEDTAXYEST     float64 `xml:"CP_PACKAGE_LED_TAX_YEST"`
	CFLOGO                  float64 `xml:"CF_LOGO"`
	CSDEPOSITTAXLEDDEBITREP float64 `xml:"CS_DEPOSIT_TAX_LED_DEBIT_REP"`
	CSOWNERLEDCREDITREP     float64 `xml:"CS_OWNER_LED_CREDIT_REP"`
	CSOWNERLEDDEBITREP      float64 `xml:"CS_OWNER_LED_DEBIT_REP"`
	CFOWNERLEDREP           float64 `xml:"CF_OWNER_LED_REP"`
	CPOWNERLEDDEBITYEST     float64 `xml:"CP_OWNER_LED_DEBIT_YEST"`
	CPOWNERLEDCREDITYEST    float64 `xml:"CP_OWNER_LED_CREDIT_YEST"`
	CFOWNERLEDYEST          float64 `xml:"CF_OWNER_LED_YEST"`
	CSDEPOSITLEDACTIVITYREP float64 `xml:"CS_DEPOSIT_LED_ACTIVITY_REP"`
	CPDEPLEDDEBITPLCZ       float64 `xml:"CP_DEP_LED_DEBIT_PL_CZ"`
}
